### ISSUE TITLE
Nette\Mail\Message::setFrom Bug

### ISSUE THREAD

**Issue by BugsBunny338** [nette/mail#10]
Following http://doc.nette.org/en/2.3/mailing, trying to

```php
$mail = new Message;
$mail->setFrom('john@example-dash-another-dash.com');
```

When domain name has several dashes, the mail is not sent. No exception thrown.

Possible workaround:

```php
$mail = new Message;
$mail->setFrom('john@example-dash-another-dash.com', NULL);
```

Server: MAMP 3.0.7.3
PHP version:  5.6.2
OS: OS X 10.10
Browser: Google Chrome

**Comment by dg** [comment]
I am unable to reproduce it.

**Comment by BugsBunny338** [comment]
Missing MX record within hosting DNS prevented the email to be sent from a "non-existing" domain. Terribly sorry for the confusion! :-( Lesson learned.
