### ISSUE TITLE
Return-path ignored

### ISSUE THREAD

**Issue by FTCP** [nette/mail#101]
This part of code is setting return-path using From value but ignoring Return-path header - there should by condition to use return-path if it was set for a message.

src/Mail/SendmailMailer.php

line 50
$cmd = $this->commandArgs;
if ($from = $mail->getFrom()) {
	$cmd .= ' -f' . key($from);
}

**Comment by milo** [comment]
You cannot set Return-Path header. Receiving MTA sets it to envelope from address.

Btw see #96
