### ISSUE TITLE
From doesn't expect localhost

### ISSUE THREAD

**Issue by vojta001** [nette/mail#17]
My application sends emails. I didn't want to hardcore the domain into it, so that I got it from HttpResponse. Unfortunately if I debug the app on a development machine and I access it through localhost as a domain, it throws
<pre>Nette\Utils\AssertionException
    The header 'From' expects to be email, string 'email@localhost' given.</pre>
I have to put there something like localhost.cz.

**Comment by JanTvrdik** [comment]
My guess is that `email@localhost` is not valid e-mail.

**Comment by vojta001** [comment]
I don't think so. The part after @ indicates the server by a domain or an IP address. Localhost is just an alias of my local IP adress, isn't it?

**Comment by nechutny** [comment]
After @ is domain (RFC 5322 section 3.4.1) and "localhost" is not domain. Also e-mails use MX records in DNS and localhost isn't resolvable by DNS.

**Comment by vojta001** [comment]
You're right, sorry. I thought that "localhost" could be used as an IP address in this context.
