### ISSUE TITLE
Delivery Status Notification

### ISSUE THREAD

**Issue by hm122** [nette/mail#20]
Hi! Are [DSNs](http://www.sendmail.org/~ca/email/dsn.html) supported? Thanks!

**Comment by milo** [comment]
It is not in [SmtpMailer](https://github.com/nette/mail/blob/622595aca2c2de290a80ffe8f410b0327495223c/src/Mail/SmtpMailer.php).

**Comment by hm122** [comment]
Can I make a pull request for it?

**Comment by milo** [comment]
Sure you can. But please describe your purpose and use-cases you want to achive, for examle in PR description.
