### ISSUE TITLE
Exception is raised when html body contains url with 'src' link

### ISSUE THREAD

**Issue by iinfo-dev-mk** [nette/mail#25]
Creating email message with html body, which contains query string with "src" name in some url, throws FileNotFoundException.

```php
$message = new Nette\Mail\Message();
$message->setHtmlBody("<a href='test.php?src=SOME'>some link</a>");
```
throws FileNotFoundException with message "Unable to read file /SOME"

Because it completely crashes sending particular email, it's serious bug.

Maybe there are another use cases with src string in html, which can also hit this bug.

**Comment by Unlink** [comment]
Problem is in this regex https://github.com/nette/mail/blob/master/src/Mail/Message.php#L227
It should be modified to st. like this
```
#\s+(src\s*=\s*|background\s*=\s*|url\()(["\']?)(?![a-z]+:|[/\\#])([^"\')\s]+)#i
```

**Comment by dg** [comment]
Workaround: `$message->setHtmlBody($html, FALSE)`

**Comment by iinfo-dev-mk** [comment]
@dg This workaround doesn't work for our case. Code example in issue description is narrowed for better tracing cause of issue.

Our case is emailing html template with some assets (images, etc) and user defined parts. Problematic url is in one of user defined part and we cannot change this one.

Be aware, that it is also security issue. Some sensitive attachments can be send when tricky html string is passed.

**Comment by dg** [comment]
Can you send pull request?

**Comment by iinfo-dev-mk** [comment]
What do you think, it's change of regexp sufficient?

There can be for example email with some html snippet witch is explanation of markup, html email body can have some `Hey, you have bad path in your image url instead of <pre><img src="/images/main.png"></pre>, it must be <pre><img scr="/images/main2.png"></pre>`

It fails also with Exception, but maybe it's another issue. 

I don't know git, but I can try to prepare pull request if regexp change is sufficient for you. For me it is.

**Comment by dg** [comment]
Content inside `<pre> must be encoded `<pre>&lt;img scr="/images/main2.png"&gt;</pre>`.
