### ISSUE TITLE
setSubject went wrong sometime

### ISSUE THREAD

**Issue by sostuts** [nette/mail#32]
when i use setSubject('sss') or setSubject('sssssssssssssssssssssss') or setSubject(s*N) , it output  "SMTP server did not accept . with error: 554……" ,    HOW ODD!!!

**Comment by dg** [comment]
I am unable to reproduce it.

**Comment by rostenkowski** [comment]
It looks like some crazy settings on the SMTP server... :(

**Comment by TomasVotruba** [comment]
@rostenkowski Were you able to reproduce it?

**Comment by dennydanek** [comment]
@dg, @TomasVotruba 
It still happen (now on seznam.cz).
I believe it is just because of delayed response from the SMTP server. Because when the response is empty It's been fixed by adding read repeatedly.

SmtpMailer.php
```
protected function write(string $line, $expectedCode = null, string $message = null): void
{
	fwrite($this->connection, $line . Message::EOL);
	if ($expectedCode) {
		$response = $this->read();
		if ($response === '') {
			$response = $this->read();
		}
		if (!in_array((int) $response, (array) $expectedCode, true)) {
			throw new SmtpException('SMTP server did not accept ' . ($message ?: $line) . ' with error: ' . trim($response));
		}
	}
}
```

**Comment by KminekMatej** [comment]
@dennydanek I recently ran into this situation as well and your hotfix helped me.
Did you suggested this as PR (or at least thought about it)?

**Comment by dg** [comment]
@KminekMatej can you try dev-master?

**Comment by KminekMatej** [comment]
Unfortunately not on production, where 99% of mails are processed. I can try it on staging environment but I dont suppose the problem's gonna appear there. I will try and let you know in case.
