### ISSUE TITLE
Extension: FalbackMailer

### ISSUE THREAD

**Issue by JanGalek** [nette/mail#44]
- [ ] bug report?
- [x] feature request?
- [x] version: 2.4 - 3.0

I create a [extension for configure FallbackMailer](https://github.com/JanGalek/MailFallback) in neon, I think, than it would be in this.

Maybe add option whitch turn on/off fallbackMailer, fallback: true/false - false by default.

**Comment by JanTvrdik** [comment]
Why close this?

**Comment by f3l1x** [comment]
Thank you @JanGalek.

I like it, but it's hard to make some decisions now. Personally, I like more-extension approach, it's easy to maintain, it's easy to read but it increate learning curve for beginners. 

It needs more review and discussion with @dg. We'll let you known.

**Comment by dg** [comment]
Be a self confidence. If you close the feature request when the random passerby puts thumb down, it means that it's so insignificant to you,  so I do not see a reason to deal with it at all.

**Comment by JanGalek** [comment]
@dg Ok, I will be a self confidence. :)
