### ISSUE TITLE
eml attachments

### ISSUE THREAD

**Issue by podolinek** [nette/mail#47]
- bug report? yes
- feature request? yes
- version: 2.4

### Wrong content type for .eml files added as attachment

Hi, if you add eml file (mail file) to mail message attachments and send, some mail servers (in my case seznam.cz) reply me:

```
You message for <...@...> from 2017/11/29 could not be delivered.
It's attached below.

Důvod / Reason:
---------------

5.6.5 ebox; ebox: bad argument: Rfc822 message part can not be conbinated with base64 encoding.
```
It noticed me about wrong content type of attachment, which is "correctly" set as Rfc822, but this content type is not allowed for attached files.

Chapter 4.4 of [whitepapers from microsoft](https://technet.microsoft.com/en-us/library/hh547013(v=exchg.141).aspx) describes how to fix it: change content-type to ```APPLICATION/OCTET-STREAM```.

This should be fine implemented at nette mail for example at Message.php.

```
public function addAttachment($file, $content = null, $contentType = null) {
	$path = $file;
	$ext = Strings::lower(pathinfo($path, PATHINFO_EXTENSION));
	if ($ext == 'eml') {
		$contentType = $contentType ?? 'APPLICATION/OCTET-STREAM';
	}
	return $this->attachments[] = $this->createAttachment($file, $content, $contentType, 'attachment');
}
```

What do you think about this change?

Regards,
Ondrej

**Comment by dg** [comment]
I fixed it a little differently, is it ok?

**Comment by podolinek** [comment]
David thanks,

great "low-level" implementation.

Ondrej
