### ISSUE TITLE
mail twice

### ISSUE THREAD

**Issue by theone-daxia** [nette/mail#48]
- bug report? yes/no
- feature request? yes/no
- version: ?.?.? 

### Description
after required this composer, every time i send email to me, i will receive email twice! why?

### Steps To Reproduce
... If possible a minimal demo of the problem ...

**Comment by milo** [comment]
I'm sorry, but probably our english is not compatible and maybe I don't undestand well.

You cannot receive email when you required this package by Composer. You have to use some code. Send and example of code here and the package version.

**Comment by theone-daxia** [comment]
`<?php

use Nette\Mail\Message;
use Nette\Mail\SendmailMailer;

class Mail extends Message
{
    public static function sendEmailToMe()
    {
        $mail = new Message;
        $mail->setFrom('haha@****.com.cn')
            ->addTo('haha@****.com.cn')
            ->setSubject('surprise')
            ->setBody('hello daxia');
        $mailer = new SendmailMailer;
        $mailer->send($mail);
    }
}`


this is my code,  i execute it , i will receive two same email from apache

**Comment by k00ni** [comment]
Hi, how and when do you call **sendMailToMe**? Maybe the function itself gets called twice?

**Comment by dg** [comment]
Imho problem is not in this library.
