### ISSUE TITLE
Return true for send()

### ISSUE THREAD

**Issue by CodeAlDente** [nette/mail#59]
Please return true on send() to check whether an email could be sent or not.

**Comment by dg** [comment]
It throws exception on error.

**Comment by CodeAlDente** [comment]
I know. But why not returning true? Doing so I can easily handle that in my application and let the user know that the email has been sent.

**Comment by milo** [comment]
Because `true` would be the only one value returned, you never get `false`.
```php
try {
  $mailer->send(...);  # <-- goes not matter what is returned
  echo "OK";
} catch (Nette\Mail\SendException $e) {
  echo "Failed";
}
```

**Comment by mhmd1983** [comment]
is this issue fixed , if not how to check for send true or false ?

**Comment by milo** [comment]
send() cannot return value when throws the exception.
