### ISSUE TITLE
Undefined index SMTP

### ISSUE THREAD

**Issue by Lumeriol** [nette/mail#60]
Version: 3.0-dev
From commit: 6e88a3ee4a0e7070c5d79422d6454bd4f74d1aa7

### Bug Description
Undefined index: smtp - on line 45 in src/Bridges/MailDI/MailExtension.php
if ($this->config['smtp']) {

### Steps To Reproduce
If throws error only sometime, on one page immediately or after some refreshes.

EDIT: It seems that there is more similar notices, Tracy report i.e. indexes 'debugger', 'users', 'roles', etc. in SecurityExtension, 'netteMailer', 'bar', 'blueScreen' in TracyExtension. 
And problems are with foreaches that use $this->config['xxx']. Seems that there is problem with missing Nette\DI\Config\Expect, that was deleted.

### Possible Solution
Check if exists index, or other solution used for config array.

**Comment by dg** [comment]
I suppose there is no problem with the stable release anymore, is it?

**Comment by Lumeriol** [comment]
Yes, this could be closed, all is correct now .
