### ISSUE TITLE
if i Use body_text & body_html & and have no attachment and use UTF-8 i have message 

### ISSUE THREAD

**Issue by vixivixi** [nette/mail#7]
OOPS

THANKS!

**Comment by fprochazka** [comment]
I don't understand your issue. Could you be more specific?

**Comment by fprochazka** [comment]
@dg I think it's a spambot.

**Comment by Majkl578** [comment]
@fprochazka: I don't think so.

**Comment by vixivixi** [comment]
Sorry i have no idea how to remove the topic if i make a mistake.

**Comment by hrach** [comment]
You should just put your solution and close the issue - it can help others in future.
