### ISSUE TITLE
Spam report: BASE64_LENGTH_79_INF

### ISSUE THREAD

**Issue by bvelastegui** [nette/mail#72]
First of all thank you very much for your work.

I comment that when sending emails with an attached pdf document mailtrap.io indicates this in your spam report:

| Pts | Rule name | Description 
|:--: |:--|:--
| 2.0 | BASE64_LENGTH_79_INF | BODY: base64 encoded email part uses line

To generate the PDF file I am using mpdf.

I did not find information about it and for this reason I go to you.

Thank you very much!

**Comment by milo** [comment]
Since this commit 856c152d8c7b45222945b788fec8c85f7f18e6ea.
Links on RFCs https://en.wikipedia.org/wiki/Base64#Variants_summary_table
