### ISSUE TITLE
Double square bracket causes error when set via setHtmlBody

### ISSUE THREAD

**Issue by jfilla** [nette/mail#76]
Version:  v3.1.4
### Bug Description

```php
$this->mailer->send(
  (new Message())
	->addTo('email@emai.com')
	->setFrom('email@email.com')
	->setHtmlBody('<p>hello [[there]] obi wan</p>', __DIR__)
);
```
will produce
```log
Unable to read file '/var/www/web-project/app/Presenters/there'. failed to open stream: No such file or directory
```

### Steps To Reproduce
Send e-mail containig [[string]] inside html body. Second parameter (basePath) of setHtmlBody must be set.

Demo: https://github.com/jfilla/nette-mail-issue/blob/master/app/Presenters/HomepagePresenter.php

### Expected Behavior
Allow to use [[string]] inside html email without error.

### Possible Solution
Dont know yet.

**Comment by dg** [comment]
Remove __DIR__ https://doc.nette.org/cs/3.0/mailing#toc-vytvoreni-e-mailu

**Comment by jfilla** [comment]
Oh, sorry I didn't notice "special syntax". I just encode brackets as html entities. Thank you.
