### ISSUE TITLE
Support self-signed certificates

### ISSUE THREAD

**Issue by jakubvojacek** [nette/mail#90]
Hello

we have some SMTP servers with self signed SSL certificates. They do not work and currently are failing due to `stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed` 

Would it be possible to add some configuration option `verify = false` to be able to make this configuration work?

Seems like laravel/symfony mailers support it (according to https://stackoverflow.com/a/61588084). It would be very nice if Nette would support it as well please.

Thank you
Jakub

**Comment by JanTvrdik** [comment]
Instead of not verifying them, you should add them to trust store.
https://www.php.net/manual/en/openssl.configuration.php

**Comment by jakubvojacek** [comment]
Thanks
