### ISSUE TITLE
To: undisclosed-recipients

### ISSUE THREAD

**Issue by krulis-martin** [nette/mail#91]
I would like to suggest a modification of `SmptMailer` to define "To:" header with `undisclosed-recipients: ;` content when Bcc was removed and no other recipient headers are sent. I have been just struggling with sendmail SMTP server that does not like it when no "To" header is set (and I need to send only anonymous notifications from my Nette app).

I think adding
```php
		if (!$tmp->getHeader('To') && !$tmp->getHeader('Cc')) {
			// missing recipient headers make some mailers (e.g., sendmail) nervous, so we set To like MTAs does
			$tmp->setHeader('To', 'undisclosed-recipients: ;');
		}
```
right after line 75 (where `$tmp->setHeader('Bcc', null);` is) in `SmptMailer.php` should do the trick...

**Comment by dg** [comment]
That makes sense, please send PR and test.

**Comment by krulis-martin** [comment]
PR #92 ready for your inspection ;)
